/*

    OpenGL loader generated by glad 0.1.33 on Tue Aug 18 13:21:28 2020.

    Language/Generator: D
    Specification: gl
    APIs: gl=4.6
    Profile: core
    Extensions:
        
    Loader: True
    Local files: False
    Omit khrplatform: False
    Reproducible: False

    Commandline:
        --profile="core" --api="gl=4.6" --generator="d" --spec="gl" --extensions=""
    Online:
        https://glad.dav1d.de/#profile=core&language=d&specification=gl&loader=on&api=gl%3D4.6
*/

module glad.gl.all;


public import glad.gl.funcs;
public import glad.gl.ext;
public import glad.gl.enums;
public import glad.gl.types;
